apiVersion: v1
kind: Pod
metadata:
  name: docker-python-pod
  labels:
    component: webserver
spec:
  containers:
  - name: docker-python-pod
    image: python:3
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "python3 -m http.server 7070" ]
